language: java
cache:
  directories:
    - $HOME/.m2
jdk: openjdk11

branches:
  only:
    - master

install: mvn package

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    on_success: never
    on_failure: always
